### ISSUE TITLE
Bug: Onchainkit Tailwind colors overwrite original project colors

### ISSUE THREAD

**Issue by rin-st** [coinbase/onchainkit#852] opened 2024-07-22 18:50 UTC
### Describe the bug and the steps to reproduce it

1. Create a project with tailwind color names the same like in `onchainkit`, for example `primary` background color

```
import path from 'node:path'; 

/** @type {import('tailwindcss').Config} */
export default {
  ...
  theme: {
    extend: {  
      backgroundColor: {  
        primary: "FF0000"
      }, 
    }, 
  },
  plugins: [],
};
```
Use this color in your project, for example some `div` with `bg-primary` className.
2. Install onchainkit
3. Follow [Onchainkit Tailwind Integration guide](https://onchainkit.xyz/guides/tailwind)
4. Your `div` styles are broken. Now it uses `primary` from `onchainkit`

### What's the expected behavior?

Integration guide doesn't break my app styles

---
Looks like the easiest solution is to rename variables and colors, and use new naming. For example
`--bg-primary` to `--bg-onchainkit-primary` and `primary` to `onchainkit-primary`

```
theme: {
    extend: {  
      backgroundColor: {  
        "onchainkit-primary": "var(--bg-onchainkit-primary)"
      }, 
    }, 
  },
```

So there will be no variables collision.

If you agree with this solution I can try to fix it next days

### What version of the libraries are you using?

0.25.6

**Comment by Zizzamia** [comment] 2024-07-22 22:32
You right!!! Ok let me fix this right away.

Thank you @rin-st for the feedback.

**Comment by Zizzamia** [comment] 2024-07-22 23:27
Actually let me take a step back. Why are you following the `Tailwindcss Integration`? That guide is meant to be used when you want to override OnchainKit colors with your colors.

In the situation you want them stay separate you should just follow the Getting Started guide and just import the style as it is.

```
import '@coinbase/onchainkit/styles.css';
```

Is that not enough?

I can see a confusion in the doc. For sure we should a bit more clear on that.

An other point is the reason why we re-use the same primary variables. That was so on purpose so that OnchainKit can inherit the default value of your Tailwind configuration.

@rin-st what do you think?

**Comment by rin-st** [comment] 2024-07-23 09:37
Thank you for a quick answer!

> Why are you following the Tailwindcss Integration? That guide is meant to be used when you want to override OnchainKit colors with your colors.

Yes, it was not clear for me since 
1) In my case colors of components was different from what I expected
> I can see a confusion in the doc. For sure we should a bit more clear on that.
2) As you mentioned it's not very clear what Tailwind integration is. For me it fixed colors of onchainkit components but broke my app colors. (This issue)
3) I'm not sure that `import '@coinbase/onchainkit/styles.css';` was mentioned on getting started guide when I started to play with onchainkit (near 0.20-0.21). But probably I just missed it

> In the situation you want them stay separate you should just follow the Getting Started guide and just import the style as it is.
> Is that not enough?

Let's consider this
1. I have these colors in my config
```
theme: {
    extend: {  
      backgroundColor: {
        primary: "#FF0000",
      },
      textColor: {
        error: "#00FF00",
      }, 
  },
```
2. I install onchainkit
3. I import styles `import '@coinbase/onchainkit/styles.css';`
4. Since I already had `primary` and `error` colors, `onchainkit` components looks not so good. 

| Result (This case) | Default colors (or with tw integration) |
|--------------------|-----------------------------------------|
| ![Screenshot-1](https://github.com/user-attachments/assets/91c40b43-cf66-4461-8728-56fcb3155893) | ![Screenshot-2](https://github.com/user-attachments/assets/b4ffec8e-c06a-44ca-b3fb-719aae8662c8) |


So the question is, how to rewrite colors of `onchainkit` without changing colors of my app? (I may want default or custom colors)

If I change let's say `primary` color, onchainkit button and "Max" text will be fixed, but my app colors will be broken again.

If I add `className` to `SwapButton`, I need to remember about `hover`/`active` etc and also I need to create a wrapper around `SwapButton` or around my `SwapComponent` so colors would be the same everywhere I use that component. Rewriting `SwapButton` color works this way, but color  of `SwapInput` text cannot be changed using `className`

Renaming vars can help again, but probably I'm missing something.

Thanks!

**Comment by Zizzamia** [comment] 2024-07-23 21:15
I am going to start exploring adding prefix here https://github.com/coinbase/onchainkit/pull/867

**Comment by Zizzamia** [comment] 2024-07-23 22:50
@rin-st let me know if `v0.26` solves your issue. If it does, than we can close this issue.

**Comment by rin-st** [comment] 2024-07-24 09:12
Almost solved, thank you very much!

There's still a little bugs, but I understand that it's not so easy to rename every className without forgetting something

How it looks now: 
![image](https://github.com/user-attachments/assets/57785312-f6a3-42b4-8579-6e9bb8520fa1)

Other than that, everything work as expected :tada:

**Comment by Zizzamia** [comment] 2024-07-24 18:14
Sweet, thank you for keep debugging this :)

Just released `v0.26.2` with that fix as well. Please let me know if you discover more location we miss the prefix colors.

**Comment by rin-st** [comment] 2024-07-24 19:50
Colors are fixed, thank you!

---

Not related to this issue, but `Identity` component is broken in `0.26.2` avatar and ENS name doesn't work (even in documentation). `0.26.0` works as expected.

**Comment by Zizzamia** [comment] 2024-07-24 23:50
Ok, great news! So I am going to close this, and check right away on the ENS story.

And make sure I add more tests for any regression we introduced. Thank you @rin-st

**Closed by Zizzamia** 2024-07-24 23:50 UTC

**Comment by Zizzamia** [comment] 2024-07-25 00:49
@rin-st try out `v0.26.3`, it should have the Identity fix.

**Comment by rin-st** [comment] 2024-07-25 08:31
Everything works great now, thank you @Zizzamia ! 🙏
