### ISSUE TITLE
Bug: @grpc/grpc-js library is only for node and causing issues in NextJS with getFrameMetadata()

### ISSUE THREAD

**Issue by M4cs** [coinbase/onchainkit#51] opened 2024-01-31 17:43 UTC
### Describe the bug and the steps to reproduce it

When importing `getFrameMetadata` from the latest `@coinbase/onchainkit` version (0.3.0) and previous version (0.2.1) fails due to @grpc/grpc-js imports.

### What's the expected behavior?

There should be no errors when importing `getFrameMetadata` to my page.tsx

### What version of the libraries are you using?

- OnchainKit: [0.3.0]

**Comment by cnasc** [comment] 2024-01-31 18:15
Tried adding a pages route using the same setup as above, and I do see failure to compile with the error you mentioned. (though error doesn't come from import, rather from calling `getFrameMetadata`). We should update docs to indicate that `getFrameMetadata` can only be called in the component in app router, for pages router it will have to be called in `getServerSideProps` or `getStaticProps`.

**Comment by Zizzamia** [comment] 2024-01-31 18:53
@cnasc, I don't believe double down on NextJS is the solution here. But instead find the right way to see where something should just work with Node vs NextJS vs client TS.

**Comment by Zizzamia** [comment] 2024-02-02 02:22
@M4cs let me know if the issue is solved with `v0.4.1`. It should, but would love your final check.

**Comment by Zizzamia** [comment] 2024-02-03 04:33
Closing this, as we noticed the issue was solved.

**Closed by Zizzamia** 2024-02-03 04:33 UTC

**Comment by zimmah** [comment] 2024-08-26 20:55
I am following this exact tutorial: https://www.pinata.cloud/blog/how-to-make-a-frame-on-farcaster-using-ipfs/

and when I do `npx create-next-app@latest frame-tutorial`, followed by `cd frame-tutorial && npm install && npm install @coinbase/onchainkit`

and then replace the boilerplate `pages.tsx` with the boilerplate from the tutorial I am getting:

`Module '"@coinbase/onchainkit"' has no exported member 'getFrameMetadata'.ts(2305)`
